name       : os-installer
version    : 17.0
release    : 122
source     :
    - https://github.com/ZVNexus/os-installer/archive/v17.tar.gz : f63dd7987d97141402433137bf07b7ab148b368d50ffa1235d94915f015f030b
homepage   : https://www.solus-project.com
license    :
    - GPL-2.0
summary    : Install OS to disk
component  : system
builddeps  :
    - python-setuptools
rundeps    :
    - gsettings-desktop-schemas
    - libgnome-desktop
    - libtimezonemap
    - python-cairo
    - python-geoip
    - python-gobject
    - python-parted
    - setxkbmap
    - f2fs-tools
description: |
    Install OS to disk
build      : |
    %python_setup
install    : |
    %python_install

    # Assets
    install -D -m 00644 dist/org.freedesktop.policykit.pkexec.policy $installdir/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    install -D -m 00755 dist/os-installer-wrapper $installdir/usr/bin/os-installer-wrapper
    install -D -m 00644 $pkgfiles/10-livecd.keyrules $installdir/usr/share/polkit-1/rules.d/10-livecd.keyrules
    install -D -m 00644 dist/install-symbolic.svg $installdir/usr/share/icons/gnome/scalable/actions/install-symbolic.svg

    # Temporary! AppSystem borkage
    install -D -m 00644 dist/com.solus_project.Installer.desktop $installdir/usr/share/applications/os-installer-gtk.desktop

    # Ensure GDM works again post-install
    install -D -m 00644 $pkgfiles/custom.conf $installdir/usr/share/os-installer/custom.conf
